/*********************************************************************************/
/************ THIS FILE IS GENERATED BY AWTK DESIGNER, DO NOT MODIFY *************/
/*********************************************************************************/
#include "awtk.h"
#include "../res/assets.inc"

#define APP_TYPE APP_DESKTOP

extern ret_t application_init(void);

extern ret_t application_exit(void);

#include "awtk_main.inc"
