import os
import sys
import platform

OS_NAME = platform.system();
env=DefaultEnvironment().Clone()
BIN_DIR=os.environ['BIN_DIR'];

env['LIBS'] = ['web_view'] + env['LIBS']
src_files = Glob('*.c')

env.Program(os.path.join(BIN_DIR, 'demo'), src_files);
